INSERT INTO circuito(nome,alias,nazione,lunghezza) VALUES
('Adelaide','Adelaide Street Circuit','AU',3.78),
('Aida','Okayama International Circuit','JP',3.70),
('Ain-Diab','Ain-Diab Circuit','MA',7.603),
('Aintree','Aintree Motor Racing Circuit','UK',4.83),
('Anderstrop','Anderstrop Raceway','SE',4.02),
('Austin','Circuit of the Americas','US',5.51),
('AVUS','AVUS','DE',8.30),
('Bahrain','Bahrain International Circuit','BH',5.41),
('Baku','Baku City Circuit','AZ',6.00),
('Brands Hatch','Brands Hatch','UK',4.27),
('Bremgarten','Circuit Bremgarten','CH',7.28),
('Buddh','Buddh International Circuit','IN',5.13),
('Buenos Aires','Autódromo Juan y Oscar Gálvez','AR',4.71),
('Bugatti','Bugatti Circuit','FR',4.43),
('Caesars Palace','Caesars Palace','US',3.65),
('Catalunya','Circuit de Barcelona-Catalunya','ES',4.66),
('Clermont Ferrand','Charade Circuit','FR',8.06),
('Dallas','Fair Park','US',3.90),
('Detroit','Detroit Street Circuit','US', 2.74),
('Dijon','Dijon-Prenois','FR',3.80),
('Donington','Donington Park','UK',4.02),
('East London','Prince George Circuit','ZA',3.92),
('Estoril','Autódromo do Estoril','PT',4.18),
('Fuji','Fuji Speedway','JP',4.56),
('Hockenheimring','Hockenheimring','DE',4.57),
('Hungaroring','Hungaroring','HU',4.38),
('Imola','Autodromo Internazionale Enzo e Dino Ferrari','IT',4.91),
('Indianapolis','Indianapolis Motor Speedway','US',4.19),
('Interlagos','Autódromo José Carlos Pace','BR',4.31),
('Istanbul','Istanbul Park','TR',5.34),
('Jacarepagua','Autódromo Internacional Nelson Piquet','BR',5.48),
('Jarama','Circuito del Jarama','ES',3.85),
('Jeddah','Jeddah Street Circuit','SA',6.17),
('Jerez','Circuito de Jerez','ES',4.43),
('Kyalami','Kyalami Racing Circuit','ZA',4.53),
('Long Beach','Long Beach','US',3.17),
('Losail','Losail International Circuit','QA',5.38),
('Magny-Cours','Circuit de Nevers Magny-Cours','FR',4.41),
('Marina Bay','Marina Bay Street Circuit','SG',4.93),
('Melbourne','Melbourne Grand Prix Circuit','AU',5.30),
('Mexico City','Autódromo Hermanos Rodríguez','MX',4.30),
('Miami','Miami International Autodrome','US',5.41),
('Monaco','Circuit de Monaco','MC',3.34),
('Monsanto','Circuito de Monsanto','PT',5.44),
('Mont-Tremblant','Circuit Mont-Tremblant','CA',4.26),
('Montjuïc','Circuito de Montjuïc','ES',3.79),
('Montreal','Circuit Gilles Villeneuve','CA',4.36),
('Monza','Autodromo Nazionale Monza','IT',5.79),
('Mosport','Canadian Tire Motorsport Park','CA',3.96),
('Mugello','Autodromo Internazionale del Mugello','IT',5.25),
('Nivelles-Baulers','Nivelles-Baulers','BE',3.72),
('Nürburgring','Nürburgring','DE',5.10),
('Paul Ricard','Circuit Paul Ricard','FR',5.84),
('Pedralbes','Pedralbes Circuit','ES',6.33),
('Pescara','Pescara Circuit','IT',25.58),
('Phoenix','Phoenix Street Circuit','US',3.72),
('Portimão','Algarve International Circuit','PT',4.35),
('Porto','Circuito da Boavista','PT',7.40),
('Reims-Gueux','Reims-Gueux','FR',7.82),
('Riverside','Riverside International Raceway','US',5.27),
('Rouen-Les-Essarts',' Rouen-Les-Essarts','FR',6.54),
('Sakhiir','Bahrain International Circuit alternative','BH',3.54),
('Sebring','Sebring International Raceway','US',6.02),
('Sepang','Sepang International Circuit','MY',5.54),
('Shanghai','Shanghai International Circuit','CN',5.45),
('Silverstone','Silverstone Circuit','UK',5.89),
('Sochi','Sochi Autodrom','RU',5.85),
('Spa-Francorchamps','Circuit de Spa-Francorchamps','BE',7.00),
('Spielberg','Red Bull Ring','AT',4.32),
('Suzuka','Suzuka Circuit','JP',5.81),
('Valencia','Valencia Street Circuit','ES',5.42),
('Watkins Glen','Watkins Glen International','US',5.44),
('Yas Marina','Yas Marina Circuit','AE',5.55),
('Yeongam','Korea International Circuit','KR',5.62),
('Zandvoort','Circuit Park Zandvoort','NL',4.26),
('Zeltweg','Zeltweg','AT',4.32),
('Zolder','Circuit Zolder','BE',4.01);