/*dal 2014 ogni pilota è associato anche ad un numero, prima 
non lo avevano, i piloti che hanno corso prima avranno NULL nel 
campo numero in gara nelle altre tabelle*/

INSERT INTO pilota(codice_fiscale,nome,cognome,sesso,nazionalita,anno_nascita,anno_morte,sigla_in_gara) VALUES
('LEHAMU85','Lewis','Hamilton'          ,'M','UK',1985,NULL,'HAM'),
('GERUMU98','George','Russell'          ,'M','UK',1998,NULL,'RUS'),
('MAVEMN97','Max','Verstappen'          ,'M','NT',1997,NULL,'VER'),
('SEPEMM90','Sergio','Pérez'            ,'M','MX',1990,NULL,'PER'),
('CASAME94','Carlos','Sainz Jr.'        ,'M','ES',1994,NULL,'SAI'),
('CHLEMM97','Charles','Leclerc'         ,'M','MC',1997,NULL,'LEC'),
('LANOMU99','Lando','Norris'            ,'M','UK',1999,NULL,'NOR'),
('DARIMA89','Daniel','Ricciardo'        ,'M','AU',1989,NULL,'RIC'),
('FEALME81','Fernando','Alonso'         ,'M','ES',1981,NULL,'ALO'),
('ESOCMF96','Esteban','Ocon'            ,'M','FR',1996,NULL,'OCO'),
('PIGAMF96','Pierre','Gasly'            ,'M','FR',1996,NULL,'GAS'),
('YUTSMJ00','Yuki','Tsunoda'            ,'M','JP',2000,NULL,'TSU'),
('SEVEMD87','Sebastian','Vettel'        ,'M','DE',1987,NULL,'VET'),
('LASTMC98','Lance','Stroll'            ,'M','CA',1998,NULL,'STR'),
('NILAMC95','Nicholas','Latifi'         ,'M','CA',1995,NULL,'LAT'),
('ALALMT96','Alexander','Albon'         ,'M','TH',1996,NULL,'ALB'),
('GUZHMC99','Guanyu','Zhou'             ,'M','CN',1999,NULL,'ZHO'),
('VABOMF89','Valtteri','Bottas'         ,'M','FI',1989,NULL,'BOT'),
('KEMAMD92','Kevin','Magnussen'         ,'M','DK',1992,NULL,'MAG'),
('MISCMD99','Mick','Schumacher'         ,'M','DE',1999,NULL,'MSC'),

('KIRAMF79','Kimi','Räikkönen'          ,'M','FI',1979,NULL,'RAI'),
('ANGIMI93','Antonio','Giovinazzi'      ,'M','IT',1993,NULL,'GIO'),
('NIMAMR99','Nikita','Mazepin'          ,'M','RU',1999,NULL,'MAZ'),
('DAKVMR94','Daniil','Kvyat'            ,'M','RU',1994,NULL,'KVY'),
('NIHUMD87','Nico','Hulkenberg'         ,'M','DE',1987,NULL,'HUL'),
('ROGRMF86','Romain','Grosjean'         ,'M','FR',1986,NULL,'GRO'),
('ROKUMP84','Robert','Kubica'           ,'M','PL',1984,NULL,'KUB'),
('SESIMR95','Sergey','Sirotkin'         ,'M','RU',1995,NULL,'SIR'),
('BRHAMA89','Brendon','Hartley'         ,'M','AU',1989,NULL,'HAR'),
('STVAMB92','Stoffel','Vandoorne'       ,'M','BE',1992,NULL,'VAN'),
('MAERMS90','Marcus','Ericsson'         ,'M','SW',1990,NULL,'ERI'),
('FEMAMB81','Felipe','Massa'            ,'M','BR',1981,NULL,'MAS'),
('JOPAMU91','Jolyon','Palmer'           ,'M','UK',1991,NULL,'PAL'),
('PAWEMD94','Pascal','Wehrlein'         ,'M','DE',1994,NULL,'WEH'),
('ESGUMM91','Esteban','Gutierrez'       ,'M','MX',1991,NULL,'GUT'),
('RIHAMI93','Rio','Haryanto'            ,'M','ID',1993,NULL,'HAR'),
('JEBUMU80','Jenson','Button'           ,'M','UK',1980,NULL,'BUT'),
('FENAMB92','Felipe','Nasr'             ,'M','BR',1992,NULL,'NAS'),
('NIROMD85','Nico','Rosberg'            ,'M','DE',1985,NULL,'ROS'),
('ROMEME91','Roberto','Merhi'           ,'M','ES',1991,NULL,'MER'),
('WISTMU91','Will','Stevens'            ,'M','UK',1991,NULL,'STE'),
('PAMAMV85','Pastor','Maldonado'        ,'M','VE',1985,NULL,'MAL'), /*2015*/
('ALROMU91','Alexander','Rossi'         ,'M','US',1991,NULL,'RSI'),
('JEVEMF90','Jean-Eric','Vergne'        ,'M','FR',1990,NULL,'VER'),
('JUBIMF89','Jules','Bianchi'           ,'M','FR',1989,2015,'BIA'),
('ADSUMD83','Adrian','Sutil'            ,'M','DE',1983,NULL,'SUT'),
('MACHMU91','Max','Chilton'             ,'M','UK',1991,NULL,'CHI'),
('KAKOMJ86','Kamui','Kobayashi'         ,'M','JP',1986,NULL,'KOB'),
('MAWEMA76','Mark','Webber'             ,'M','AU',1976,NULL,'WEB'),
('PADIMU86','Paul','Di Resta'           ,'M','UK',1986,NULL,'DIR'),
('CHPIMF90','Charles','Pic'             ,'M','FR',1990,NULL,'PIC'),
('HEKOMF81','Heikki','Kovalainen'       ,'M','FI',1981,NULL,'KOV'),
('GIVAMN85','Giedo','Van der Garde'     ,'M','NL',1985,NULL,'VDG'),
('BRSEMB83','Bruno','Senna'             ,'M','BR',1983,NULL,'SEN'),
('VIPEMR84','Vitaly','Petrov'           ,'M','RU',1984,NULL,'PET'),
('TIGLMD82','Timo','Glock'              ,'M','DE',1982,NULL,'GLO'),
('JEDAMB85','Jérôme','Dambrosio'        ,'M','BE',1985,NULL,'DAM'),
('NAKAMI77','Narain','Karthikeyan'      ,'M','IN',1977,NULL,'KAR'),
('PEDEME71','Pedro','De la Rosa'        ,'M','ES',1971,NULL,'DLR'),
('MISCMD69','Michael','Schumacher'      ,'M','DE',1969,NULL,'MSC'),
('NIHEMD77','Nick','Heidfeld'           ,'M','DE',1977,NULL,'HEI'),
('JAALME90','Jaime','Alguersuari'       ,'M','ES',1990,NULL,'ALG'),
('SEBUMC88','Sébastien','Buemi'         ,'M','CH',1988,NULL,'BUE'),
('RUBAMB72','Rubens','Barrichello'      ,'M','BR',1972,NULL,'BAR'),
('JATRMI74','Jarno','Trulli'            ,'M','IT',1974,NULL,'TRU'),
('VILIMI80','Vitantonio','Liuzzi'       ,'M','IT',1980,NULL,'LIU'),
('KACHMI84','Karun','Chandhok'          ,'M','IN',1984,NULL,'CHD'),
('LUDIMB84','Lucas','Di Grassi'         ,'M','BR',1984,NULL,'DIG'),
('NAYAMJ88','Naoki','Yamamoto'          ,'M','JP',1988,NULL,'YAM'),
('CHKLMA83','Christian','Klien'         ,'M','AT',1983,NULL,'KLI'),
('SEBOMF79','Sébastien','Bourdais'      ,'M','FR',1979,NULL,'BOU'),
('KANAMJ85','Kazuki','Nakajima'         ,'M','JP',1985,NULL,'NAK'),
('NEPIMB85','Nelson','Piquet Jr.'       ,'M','BR',1985,NULL,'PIQ'),
('LUBAMI71','Luca','Badoer'             ,'M','IT',1971,NULL,'BAD'),
('DACOMU71','David','Coulthard'         ,'M','UK',1971,NULL,'COU'),
('GIFIMI73','Giancarlo','Fisichella'    ,'M','IT',1973,NULL,'FIS'),
('TASAMJ77','Takuma','Sato'             ,'M','JP',1977,NULL,'SAT'),
('ANDAMU79','Anthony','Davidson'        ,'M','UK',1979,NULL,'DAV'),
('ALWUMA74','Alexander','Wurz'          ,'M','AT',1974,NULL,'WUR'),
('RASCMD75','Ralf','Schumacher'         ,'M','DE',1975,NULL,'RSC'),
('SCSPMU83','Scott','Speed'             ,'M','US',1983,NULL,'SPE'),
('SAYAMJ82','Sakon','Yamamoto'          ,'M','JP',1982,NULL,'YAM'),
('CHALMN79','Christijan','Albers'       ,'M','NL',1979,NULL,'ALB'),
('JUPAMC75','Juan Pablo','Montoya'      ,'M','CO',1975,NULL,'MOY'),
('JAVIMC71','Jacques','Villeneuve'      ,'M','CA',1971,NULL,'VIL'),
('TIMOMP76','Tiago','Monteiro'          ,'M','PT',1976,NULL,'MON'),
('RODOMN81','Robert','Doornbos'         ,'M','NL',1981,NULL,'DOO'),
('YUIDMJ75','Yuji','Ide'                ,'M','JP',1975,NULL,'IDE'),
('FRMOMF78','Franck','Montagny'         ,'M','FR',1978,NULL,'MON'),
('PAFRMA80','Patrick','Friesacher'      ,'M','AT',1980,NULL,'FRI'),
('ANPIMB80','Antônio','Pizzonia'        ,'M','BR',1980,NULL,'PIZ'),
('OLPAMF66','Olivier','Panis'           ,'M','FR',1966,NULL,'PAN'),
('CRDAMB73','Cristiano','Da Matta'      ,'M','BR',1973,NULL,'DAM'),
('ZSBAMH81','Zsolt','Baumgartner'       ,'M','HU',1981,NULL,'BAU'),
('RIZOMB76','Ricardo','Zonta'           ,'M','BR',1976,NULL,'ZON'),
('MAGEME74','Marc','Gené'               ,'M','ES',1974,NULL,'GEN'),
('GIPAMI79','Giorgio','Pantano'         ,'M','IT',1979,NULL,'PAN'),
('GIBRMI81','Gianmaria','Bruni'         ,'M','IT',1981,NULL,'BRU'), /*2004*/



('MADEFI26','Maria Teresa','De Filippis','F','IT',1926,2016,'DEF'),/*donne*/
('LELOFI41','Lella','Lombardi'          ,'F','IT',1941,1992,'LOM'),
('DIGAFU44','Divina','Galica'           ,'F','UK',1944,NULL,'GAL'),
('DEWIFZ53','Desiré','Wilson'           ,'F','ZA',1953,NULL,'WIL'),
('GIAMFI59','Giovanna','Amati'          ,'F','IT',1959,NULL,'AMA'),

('AYSEMB60','Ayrton','Senna'            ,'M','BR',1960,1994,'SEN'),/*migliori morti*/
('NILAMA49','Niki','Lauda'              ,'M','AT',1949,2019,'LAU'),
('RORAMA60','Roland','Ratzenberger'     ,'M','AT',1960,1994,'RAT'),
('NIFAMI06','Nino','Farina'             ,'M','IT',1906,1966,'FAR');