INSERT INTO squadra(nome,nazione,nome_precedente) VALUES
('Adams','US','-'),
('AFM','DE','-'),
('AGS','FR','-'),
('Alfa Romeo','IT','Sauber_2'),
('Alfa Special','ZA','-'),
('AlphaTauri','IT','Toro Rosso'),
('Alpine','FR','Renault_2'),
('Alta','UK','-'),
('Amon','NZ','-'),
('Andrea Moda','IT','Coloni'),
('Apollon','CH','-'),
('Arrows_1','UK','-'),
('Arrows_2','UK','Footwork'),
('Arzani-Volpini','IT','-'),
('Aston Butterworth','UK','-'),
('Aston Martin','UK','Racing Point'),
('ATS','DE','-'),
('Balsa','DE','-'),
('BAR','UK','Tyrrell'),
('Behra-Porsche','DE','-'),
('Bellasi','IT','-'),
('Benetton','IT','Toleman'),
('BMW Sauber','DE','Sauber_1'),
('BMW','DE','-'),
('Boro','NL','-'),
('Brabham','UK','-'),
('Brawn','UK','Honda'),
('BRM','UK','-'),
('Bromme','US','-'),
('BRP','UK','-'),
('Bugatti','FR','-'),
('Caterham','MY','Lotus Racing'),
('Christensen','US','-'),
('Cisitalia','IT','-'),
('Coloni','IT','-'),
('Connaught','UK','-'),
('Connew','UK','-'),
('Cooper','UK','-'),
('Dallara','IT','-'),
('De Tomaso','IT','-'),
('Deidt','US','-'),
('Del Roy','US','-'),
('Derrington-Francis','UK','-'),
('Dunn','US','-'),
('Eagle','US','-'),
('Eifelland','DE','-'),
('Elder','US','-'),
('Emeryson','UK','-'),
('EMW','DE','-'),
('ENB','BE','-'),
('Ensign','UK','-'),
('Epperly','US','-'),
('ERA','UK','-'),
('EuroBrun','IT','-'),
('Ewing','US','-'),
('Ferguson','UK','-'),
('Ferrari','IT','-'),
('FIRST','IT','-'),
('Fittipaldi','BR','-'),
('Fondmetal','IT','Osella'),
('Footwork','UK','Arrows_1'),
('Force India','IN','Spyker'),
('Forti','IT','-'),
('Frank Williams Racing Cars','UK','Iso-Marlboro'),
('Frazer-Nash','UK','-'),
('Fry','UK','-'),
('Gilby','UK','-'),
('Gordini','FR','-'),
('Greifzu','DE','-'),
('Haas','US','-'),
('Hall','US','-'),
('Heck','DE','-'),
('Hesketh','UK','-'),
('Hill','UK','-'),
('Honda','JP','BAR'),
('HRT','ES','-'),
('HWM','UK','-'),
('Iso-Marlboro','UK','Politoys'),
('Jaguar','UK','Stewart'),
('JBW','UK','-'),
('Jordan','IE','-'),
('Kauhsen','DE','-'),
('Klenk','DE','-'),
('Kojima','JP','-'),
('Krakau','DE','-'),
('Kurtis','US','-'),
('Kuzma','US','-'),
('Lancia','IT','-'),
('Langley','US','-'),
('Larrousse','FR','-'),
('LDS','ZA','-'),
('LEC','UK','-'),
('Lesovsky','US','-'),
('Leyton House','UK','March_1'),
('Life','IT','-'),
('Ligier','FR','-'),
('Lola','UK','-'),
('Lotus F1','UK','Renault_1'),
('Lotus Racing','MY','-'),
('Lotus','UK','-'),
('Lyncar','uk','-'),
('Maki','jp','-'),
('Manor','UK','Marussia'),
('March_1','UK','-'),
('March_2','UK','Leyton House'),
('Marchese','US','-'),
('Martini','FR','-'),
('Marussia','UK','Virgin'),
('Maserati','IT','-'),
('Matra','FR','-'),
('McGuire','AU','-'),
('McLaren','UK','-'),
('Mercedes','DE','Brawn'),
('Merzario','IT','-'),
('Meskowski','US','-'),
('Midland','RU','Jordan'),
('Minardi','IT','-'),
('Modena','IT','-'),
('Moore','US','-'),
('Nacke','DE','-'),
('Nichels','US','-'),
('Olson','US','-'),
('Onyx','UK','-'),
('O.S.C.A.','IT','-'),
('Osella','IT','-'),
('Pacific','UK','-'),
('Pankratz','US','-'),
('Parnelli','US','-'),
('Pawl','US','-'),
('Penske','US','-'),
('Phillips','US','-'),
('Politoys','UK','-'),
('Porsche','DE','-'),
('Prost','FR','Ligier'),
('Protos','UK','-'),
('Racing Point','UK','Force India'),
('Rae','US','-'),
('RAM','UK','-'),
('Rebaque','MX','-'),
('Red Bull','AT','Jaguar'),
('Renault','FR','Benetton'),
('Rial','DE','-'),
('Sauber_1','CH','-'),
('Sauber_2','CH','BMW Sauber'),
('Scarab','US','-'),
('Schroeder','US','-'),
('Scirocco','UK','-'),
('Shadow','UK','-'),
('Shannon','UK','-'),
('Sherman','US','-'),
('Simca-Gordini','FR','-'),
('Simtek','UK','-'),
('Snowberger','UK','-'),
('Spirit','UK','-'),
('Spyker','NL','Midland'),
('Stebro','CA','-'),
('Stevens','US','-'),
('Stewart','UK','-'),
('Super Aguri','JP','-'),
('Surtees','UK','-'),
('Sutton','US','-'),
('Talbot-Lago','FR','-'),
('Tec-Mec','US','-'),
('Tecno','IT','-'),
('Theodore','HK','-'),
('Token','UK','-'),
('Toleman','UK','-'),
('Toro Rosso','IT','Minardi'),
('Toyota','JP','-'),
('Trevis','US','-'),
('Trojan','UK','-'),
('Turner','US','-'),
('Tyrrell','UK','-'),
('Vanwall','UK','-'),
('Venturi','FR','-'),
('Veritas','DE','-'),
('Virgin','UK','-'),
('Watson','US','-'),
('Wetteroth','US','-'),
('Williams','UK','-'),
('Wolf-Williams','UK','Frank Williams Racing Cars'),
('Wolf','CA','Wolf-Williams'),
('Zakspeed','DE','-');