INSERT INTO squadra(nome,nazione,nome_precedente) VALUES
('Adams','US','-'),
('AFM','DE','-'),
('AGS','FR','-'),
('Alfa Romeo','IT','Sauber_2'),
('Alfa Special','ZA','-'),
('AlphaTauri','IT','Toro Rosso'),
('Alpine','FR','Renault_2'),
('Alta','UK','-'),
('Amon','NZ','-'),
('Andrea Moda','IT','Coloni'),
('Apollon','CH','-'),
('Arrows_1','UK','-'),
('Arrows_2','UK','Footwork'),
('Arzani-Volpini','IT','-'),
('Aston Butterworth','UK','-'),
('Aston Martin','UK','Racing Point'),
('ATS','DE','-'),
('Balsa','DE','-'),
('BAR','UK','Tyrrell'),
('Behra-Porsche','DE','-'),
('Bellasi','IT','-'),
('Benetton','IT','Toleman'),
('BMW Sauber','DE','Sauber_1'),
('BMW','DE','-'),
('Boro','NL','-'),
('Brabham','UK','-'),
('Brawn','UK','Honda'),
('BRM','UK','-'),
('Bromme','US','-'),
('BRP','UK','-'),
('Bugatti','FR','-'),
('Caterham','MY','Lotus Racing'),
('Christensen','US','-'),
('Cisitalia','IT','-'),
('Coloni','IT','-'),
('Connaught','UK','-'),
('Connew','UK','-'),
('Cooper','UK','-'),
('Dallara','IT','-'),
('De Tomaso','IT','-'),
('Deidt','US','-'),
('Del Roy','US','-'),
('Derrington-Francis','UK','-'),
('Dunn','US','-'),
('Eagle','US','-'),
('Eifelland','DE','-'),
('Elder','US','-'),
('Emeryson','UK','-'),
('EMW','DE','-'),
('ENB','BE','-'),
('Ensign','UK','-'),
('Epperly','US','-'),
('ERA','UK','-'),
('EuroBrun','IT','-'),
('Ewing','US','-'),
('Ferguson','UK','-'),
('Ferrari','IT','-'),
('FIRST','IT','-'),
('Fittipaldi','BR','-'),
('Fondmetal','IT','Osella'),
('Footwork','UK','Arrows_1'),
('Force India','IN','Spyker'),
('Forti','IT','-'),
('Frank Williams Racing Cars','UK','Iso-Marlboro'),
('Frazer-Nash','UK','-'),
('Fry','UK','-'),
('Gilby','UK','-'),
('Gordini','FR','-'),
('Greifzu','DE','-'),
('Haas','US','-'),
('Hall','US','-'),
('Heck','DE','-'),
('Hesketh','UK','-'),
('Hill','UK','-'),
('Honda','JP','BAR'),
('HRT','ES','-'),
('HWM','UK','-'),
('Iso-Marlboro','UK','Politoys'),
('Jaguar','UK','Stewart'),
('JBW','UK','-'),
('Jordan','IE','-'),
('Kauhsen','DE','-'),
('Klenk','DE','-'),
('Kojima','JP','-'),
('Krakau','DE','-'),
('Kurtis','US','-'),
('Kuzma','US','-'),
('Lancia','IT','-'),
('Langley','US','-'),
('Larrousse','FR','-'),
('LDS','ZA','-'),
('LEC','UK','-'),
('Lesovsky','US','-'),
('Leyton House','UK','March_1'),
('Life','IT','-'),
('Ligier','FR','-'),
('Lola','UK','-'),
('Lotus F1','UK','Renault_1'),
('Lotus Racing','MY','-'),
('Lotus','UK','-'),
('Lyncar','uk','-'),
('Maki','jp','-'),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),
('','',''),